freebsd_task:
  env:
    GOFLAGS: -mod=vendor
  
  freebsd_instance:
    image: freebsd-11-2-release-amd64

  install_script: pkg install -y go gcc git
  test_script: make test

linux386_task:
  container:
    image: i386/centos:7
  env:
    matrix:
      - GOVERSION: 1.12
      - GOVERSION: 1.13
      - GOVERSION: 1.14
  test_script:
    -  wget https://dl.google.com/go/go${GOVERSION}.linux-386.tar.gz
    -  tar -C /usr/local -xzf go${GOVERSION}.linux-386.tar.gz
    -  export PATH=$PATH:/usr/local/go/bin
    -  go version
    -  uname -a
    -  make test
    -  cd pkg/proc
    -  for ((i=1; i<=150; i++)); do go test -test.run TestStepConcurrentDirect ; done
