language: go
sudo: required

os:
  - linux

arch:
  - amd64

go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - export GOFLAGS=-mod=vendor
  - if [ $TRAVIS_OS_NAME = "linux" ]; then sudo apt-get -qq update; sudo apt-get install -y dwz; echo "dwz version $(dwz --version)"; fi

#script: >-
#  go version &&
#  uname -a &&
#  cd pkg/proc &&
#  for ((i=1; i<=600; i++)); do go test -v -test.run TestStepConcurrentDirect ; done


# 386 linux
jobs:
  include:
    -  os: linux
       services: docker
       env: go_32_version=1.14
    -  os: linux
       services: docker
       env: go_32_version=1.13
    -  os: linux
       services: docker
       env: go_32_version=1.12

script: >-
    if [ $TRAVIS_OS_NAME = "linux" ] && [ $go_32_version ]; then
      docker pull i386/centos:7;
      docker run -v $(pwd):/delve -e GOVERSION=$go_32_version --privileged i386/centos:7 /bin/bash -c "set -x && \
           cd delve && \
           yum -y update && yum -y upgrade && \
           yum -y install wget make git gcc && \
           wget -q https://dl.google.com/go/go${GOVERSION}.linux-386.tar.gz && \
           tar -C /usr/local -xzf go${GOVERSION}.linux-386.tar.gz && \
           export PATH=$PATH:/usr/local/go/bin && \
           go version && \
           go env && \
           uname -a && \
           make test";
    else
      make test;
    fi


cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
