language: go
sudo: required

os:
  - linux
  - osx

go:
  - tip
  - 1.7
  - 1.6

install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then sudo bash -c 'echo core > /proc/sys/kernel/core_pattern'; fi

matrix:
  allow_failures:
    - go: tip
